"""Headless Factory Mode primitives for Residual's multi-swarm platform."""

from .compiler import CompileResult, RequirementCompiler
from .models import ExecutionPlan, FactoryTask, FrozenPlan, Requirement
from .evidence_bus import (
    ArtifactBinding, EvidenceBus, EvidenceError, FactoryStationIssuer,
    StationIdentity, VerificationDecision, WorkerReceipt,
)
from .m4_evidence import (
    EvidenceIntegrationPlan,
    IntegrationConflict,
    M4EvidenceError,
    PlannedArtifact,
    ReadyDagSnapshot,
    ReceiptBackedM4,
)
from .m4_integrator import (
    ConflictResolution,
    DeterministicIntegrator,
    IntegrationConflictError,
    IntegrationOutcome,
    IntegrationReceipt,
    M4IntegrationError,
    ProjectVerificationError,
    ProjectVerificationPolicy,
    VerificationCommand,
    VerificationResult,
)
from .m4_scheduler import (
    EnginePlacement,
    M4AdaptiveScheduler,
    M4SchedulerError,
    SchedulerAction,
    SchedulerCapacity,
    SchedulerMeasurements,
    SchedulerNode,
    SchedulerPolicy,
    StructuralReplanProposal,
)

__all__ = [
    "CompileResult",
    "ExecutionPlan",
    "FactoryTask",
    "FrozenPlan",
    "Requirement",
    "RequirementCompiler",
    "ArtifactBinding",
    "EvidenceBus",
    "EvidenceError",
    "FactoryStationIssuer",
    "StationIdentity",
    "VerificationDecision",
    "WorkerReceipt",
    "EvidenceIntegrationPlan",
    "IntegrationConflict",
    "M4EvidenceError",
    "PlannedArtifact",
    "ReadyDagSnapshot",
    "ReceiptBackedM4",
    "ConflictResolution",
    "DeterministicIntegrator",
    "IntegrationConflictError",
    "IntegrationOutcome",
    "IntegrationReceipt",
    "M4IntegrationError",
    "ProjectVerificationError",
    "ProjectVerificationPolicy",
    "VerificationCommand",
    "VerificationResult",
    "EnginePlacement",
    "M4AdaptiveScheduler",
    "M4SchedulerError",
    "SchedulerAction",
    "SchedulerCapacity",
    "SchedulerMeasurements",
    "SchedulerNode",
    "SchedulerPolicy",
    "StructuralReplanProposal",
]
